inmakes_product_folder/movieproject/movieapp/urls.py
from django.urls import path
from . import views
app_name='movieapp'

urlpatterns = [

    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/', views.add_movie, name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/', views.delete, name='delete'),



]

inmakes_product_folder/movieproject/movieproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("movieapp.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

inmakes_product_folder/movieproject/movieapp/models.py
from django.db import models

# Create your model
class movie(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')


    def __str__(self):
        return self.name

inmakes_product_folder/movieproject/movieapp/forms.py
from django import forms
from .models import movie

class MovieForm(forms.ModelForm):
    class Meta:
        model=movie
        fields=['name','desc','year','img']

inmakes_product_folder/movieproject/movieapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from . models import movie
from .forms import MovieForm
# Create your views here.
def index(request):
    movies=movie.objects.all()
    context={
        'movie_list':movies
    }
    return render(request,"index.html",context)
def detail(request,movie_id):
    movies=movie.objects.get(id=movie_id)

    return render(request,"detail.html",{'movies':movies})
def add_movie(request):
    if request.method == 'POST':

        name=request.POST.get('name', )
        desc = request.POST.get('desc', )
        year = request.POST.get('year', )
        img = request.FILES['img']
        movies=movie(name=name,desc=desc,year=year,img=img)
        movies.save()

    return render(request,'add.html')

def update(request,id):
    movies=movie.objects.get(id=id)
    form=MovieForm(request.POST or None, request.FILES,instance=movies )
    if form.is_valid():

        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form, 'movie':movies})
def delete(request,id):
    if request.method=='POST':
        movies=movie.objects.get(id=id)
        movies.delete()
        return redirect('/')
    return render(request,'delete.html')

inmakes_product_folder/movieproject/templates/add.html
{% extends 'base.html' %}
{% block body %}

<form method="POST"  enctype="multipart/form-data">
    {% csrf_token %}

    <input type="text" name="name"  placeholder="enter your movie name">
    <input type="text" name="desc"  placeholder="enter the movie description">
    <input type="text" name="year"  placeholder="enter your movie year">
    <input type="file" name="img">
    <input type="submit">

</form>
{% endblock %}

inmakes_product_folder/movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Just an image -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
<!--<a href="http://127.0.0.1:8000/add"><input type="button" value="add movies"></a>-->

    <h2 style="background-color:yellow;" >online movie page</h2>



  </a>
</nav>
{% block body %}
{% endblock %}

</body>
</html>

inmakes_product_folder/movieproject/templates/delete.html
<form method="POST">
  {%csrf_token %}
  Are you want to delete this movie?
  <input type="submit">
</form>

inmakes_product_folder/movieproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">

           <img src="{{movies.img.url}}" width="300" height="300">

        </div>
        <div class="col-md-6">

            <h6>{{movies.name}}</h6>
            <h4>{{movies.desc}}</h4>
            <h6>{{movies.year}}</h6>
            <a class= "btn btn-warning" href="{% url 'movieapp:update' movies.id %}">update</a>
            <a class= "btn btn-danger" href="{% url 'movieapp:delete' movies.id %}">delete</a>







           </div>
    </div>
</div>

{% endblock %}

inmakes_product_folder/movieproject/templates/edit.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

inmakes_product_folder/movieproject/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-md-3">
            <div class="card">
  <img class="card-img-top" src="{{i.img.url}}" alt="" height="250">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.desc}}</p>

<a href="{% url 'movieapp:detail' i.id %}" class="btn btn-warning">view details</a>


  </div>
</div>




        </div>
        {% endfor %}
    </div>
</div>


{% endblock %}